[package]
name = "toml_const"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "toml_const_codegen"
path = "src/main.rs"

[dependencies]
toml = "0.8.8"
clap = {version ="4.4.8", features = [ "derive" ]}


[build-dependencies]
toml = "0.8.8"
