[package]
name = "toml_const"
version = "0.1.0"
edition = "2021"
description = "Compile-time constants from TOML"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "toml_const_codegen"
path = "src/main.rs"

[dependencies]
toml = "0.8"
clap = {version ="4.4.8", features = [ "derive" ]}
log = "0.4"
pretty_env_logger = "0.5"
